library(tidyverse)

###############################################################################################################################################################################################
# Chapter 7: Positioning
###############################################################################################################################################################################################
# 7.1 Introduction
###############################################################################################################################################################################################
# There are four components that control positions:
# 1. Position adjustments adjust the position of overlapping objects within a layer. This is useful for bar and other interval geoms, but can be useful in other situations
# 2. Position scales control how the values in the data are mapped to positions on the plot
# 3. Faceting is a mechanism for automatically laying out multiple plots on a page. It splits the data into subsets, and the plots each subset in a different panel. Such plots are called small multipes or trellis graphics
# 4. Coordinate systems control how the two independent position scales are combined to create a 2d coordinate system. The most common coordinate system is Cartesian, but other coordinate systems can be useful in special circumstances

###############################################################################################################################################################################################
# 7.2 Faceting
###############################################################################################################################################################################################
# Faceting generates small multiples each showing a different subset of the data. 
# Small multiples are useful for exploratory data analysis. They allow for the rapid comparison of patterns in different parts of the data

# There are three different types of faceting:
# 1. facet_null() - A single plot, the default
# 2. facet_wrap() - "Wraps" a 1d ribbon of panels into 2d
# 3. facet_grid() Produces a 2d grid of panels defined by variables which form the rows and columns

# Faceted plots have the capability to fill up a lot of space, so it's easier to use a subset of the data that has a manageable number of levels

mpg2 <- subset(mpg, cyl !=5 & drv %in% c("4", "f") & class != "2seater")

###############################################################################################################################################################################################
# 7.2.1 Facet Wrap
###############################################################################################################################################################################################
# Facet_wrap() makes a long ribbon of panels (generated by any number of variables) and wraps it into 2d. 
# This is useful if the data contains a single variable with many levels and needs to be arranged in a space efficient manner

# The wrapping of the ribbon onto the grid can be controlled with ncol, nrow, as.table and dir.
# ncol and nrow control how many columns and rows (only one needs to be set) appear
# as.table controls whether the facets are laid out like a table (TRUE), with the highest values at the bottom-right, or a plot (FALSE) with the highest values at the top-right
# dir controls the direction of wrap horizontal or vertical

base <- ggplot(mpg2, aes(displ, hwy)) + 
  geom_blank() +
  xlab(NULL) +
  ylab(NULL)

base + facet_wrap(~class, ncol = 3) # A facet wrapped plot with 3 columns. Each column contains 2 variables since there are 6 total types of class variables
base + facet_wrap(~class, ncol = 3, as.table = FALSE)  # Changes the order which the variables appear
base + facet_wrap(~class, nrow = 3) # A facet plot that contains 3 rows
base + facet_wrap(~class, nrow = 3, dir = "v") # Changes the order of the plots since the direction of the wrapping was changed

###############################################################################################################################################################################################
# 7.2.2 Facet Grid
###############################################################################################################################################################################################
# facet_grid() lays out plots in a 2d grid, as defined by a formula:
# .~var spreads the values of "var" across the columns. The direction facilitates comparisons of y position, because the vertical scales are aligned

base + facet_grid(.~cyl) # A facet plot with all of the levels of "cyl". There are three columns because it is comparing the vertical scales of the variables

# var.~ spreads the values of "var" down the rows. This direction facilitates the comparison of x position because the horizontal scales are aligned. This make it useful for comparing distributions

base + facet_grid(drv ~.) # A facet plot with all of the levels of "drv". It is one column with 2 rows since this drv contains two levels. They are aligned the y axis

# var1 ~. var2 spreads "var1" across columns and "var2" down rows. The variable with the greatest number of levels should be placed in the columns to take advantage of the aspect ratio of a screen

base + facet_grid(drv ~ cyl) # A facet plot with 3 columns and 2 rows

# Multiple variables in the rows or columns can be added together "a + b ~ c + d". Variables appearing together on the rows or columns are nested in the sense that only combinations that appear in the data will appear in the plot
# Variables that are specified on rows and columns will be crossed: all combinations will be shown including those that didn't appear in the original dataset: this may result in empty panels

###############################################################################################################################################################################################
# 7.2.3 Controlling Scales
###############################################################################################################################################################################################
# For both facet_wrap() and facet_grid() the position of the scales can be altered so the scales are the same (fixed) or varied between panels (free) with the scales parameter:
# scales = "fixed": x and y scales are fixed across all panels
# scales = "free_x": the x scale is free while the y scale is fixed
# scales = "free_y": the y scale is free while the x scale is fixed
# scales = "free": x and y scales vary across panels

# facet_grid() imposes an additional constraint on the scales: all panels in a column must have the same x scale, and all panels in a row must have the same y scale. This is because each column shares an x axis, and each row shares a y axis

# Fixed scales make it easier to see patterns across panels; free scales make it easier to see patterns within panels

p <- ggplot(mpg2, aes(cty, hwy)) + geom_abline() + geom_jitter(width = 0.1, height = 0.1)

p + facet_wrap(~cyl)

p + facet_wrap(~cyl, scales = "free")

# Free scales are useful for displaying multiple time series that were measured on different scales
# To do this the data has to be changed from "wide" to "long" data, stacking the separate variables into a single column

economics_long

ggplot(economics_long, aes(date, value)) + geom_line() + facet_wrap(~ variable, scales = "free_y", ncol = 1)

# facet_grid() has an additional parameter called space, which takes the same values as scales. When space is "free", each column (or row) will have width (or height) proportional to the range of the scale for that column ( or row)
# This makes the scaling equal across the whole plot. This is most useful for categorical scales where space can be assigned proportionally based on the number of levels in each facet. 

mpg2$model <- reorder(mpg2$model, mpg2$cty)
mpg2$manufacturer <- reorder(mpg2$manufacturer, -mpg2$cty)
ggplot(mpg2, aes(cty, model)) +
  geom_point() +
  facet_grid(manufacturer~. , scales = "free", space = "free") +
  theme(strip.text.y = element_text(angle = 0))

###############################################################################################################################################################################################
# 7.2.4 Missing Faceting Variables
###############################################################################################################################################################################################
# When faceting a plot with multiple datasets, occasionally some of the datasets may be missing a faceting variable. 
# GGplot will display the map in every facet: missing faceting variables are treated like they have all values

df1 <- data.frame(x = 1:3, y = 1:3, gender = c("f", "f", "m"))
df2 <- data.frame(x = 2, y = 2)

ggplot(df1, aes(x, y)) + geom_point(data = df2, color = "red", size = 2) + geom_point() + facet_wrap(~gender)

# This technique is useful when adding annotations to make it easier to compare between facets

###############################################################################################################################################################################################
# 7.2.5 Grouping vs. Faceting 
###############################################################################################################################################################################################




